version: "3.3"
services:
  backend:
    container_name: myapp_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfiles
    volumes:
      - ./backend:/app/backend/
    ports:
      - "8888:8888"
    tty: 
      true
    entrypoint:
      ["poetry", "run", "uvicorn", "api/app:app", "--host", "0.0.0.0", "--port", "8888", "--reload"]

  frontend:
    container_name: myapp_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend/
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    entrypoint:
      sh -c "npm start" 


  postgresql:
    container_name: myapp_postgresql
    build:
      context: .
      dockerfile: ./postgresql/Dockerfile
    ports:
      - 5430:5430
    env_file:
          - ./postgresql/.env

  jupyter_lab:
    container_name: myapp_jupyter_lab
    build:
      context: .
      dockerfile: ./jupyterLab/Dockerfile
    volumes:
      - ./jupyterLab:/app/jupyterLab/
    ports:
      - "7777:7777"
    tty: 
      true
    entrypoint:
      ["poetry", "run", "jupyter-lab", "--ip='0.0.0.0'", "--port=7777", "--allow-root", "--no-browser", "--notebook-dir=/app/jupyterLab/", "--NotebookApp.token=''"]
    